name: Sean D. Wheeler
avatar: images/OnIT-noborder.png
bio: 'PowerShell documentarian'
# HTML markup are supported, such as: <a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>.
company: Microsoft
# HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
location: 'Denton, TX'
# The external about page. The internal about page will be used if not set.
# about: https://razonyang.com
params: {
  layout: compact
}
# See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.
social:
  # email: swsamwa@live.com
  linkedin: scriptingsean
  github: sdwheeler
  mastodon: https://sdwheeler@fosstodon.org
  twitter: swsamwa
  rss: "" # Remove RSS
  website: https://sessionize.com/sean-wheeler
