### https://gohugo.io/getting-started/configuration/
archetypeDir: archetypes
assetDir: assets
baseUrl: https://sdwheeler.github.io/seanonit/
# cacheDir: C:\Users\sewhee\AppData\Local\hugo_cache
capitalizeListTitles: true
contentDir: content
copyright: Copyright © 2014-{year} Sean D. Wheeler. All Rights Reserved.
dataDir: data
defaultContentLanguage: en
enableEmoji: true
enableRobotsTxt: true
environment: production
i18nDir: i18n
layoutDir: layouts
mainSections:
  - blog
  - posts
paginate: 10
pluralizeListTitles: true
publishDir: public
resourceDir: resources
staticDir:
  - static
summaryLength: 70
themesDir: themes
timeout: 30s
timezone: America/Chicago
title: Sean on IT
titleCaseStyle: chicago
# workingDir: D:\Git\My-Repos\seanonit
pagination:
  pagerSize: 10
  path: page
