main:
  - name: 'Talks'
    pageRef: /docs
    weight: -108
  - name: Books
    pageRef: '/reading-list'
    weight: -107
  - name: About
    pageRef: /about
    weight: -106

########################################################################################
## Menu documentation: https://gohugo.io/content-management/menus/#properties-front-matter
## The name of menu
# name:
# identifier:     ## The ID of menu.
# weight:         ## The weight of menu that used for sorting in ascending order.
# parent:         ## The `identifier` of parent menu entry.
# url:            ## The URL of menu.
# pre:            ## The leading string before menu name.
# post:           ## The trailing string after menu name.
# params:         ## Menu parameters.
#   divider:      ## true means divider.
#   icon:         ## The icon HTML.
#   description:  ## The description for top app bar dropdown menus only.