main:
  - name: 'Presentations'
    pageRef: /docs
    weight: -108
  - name: Books
    pageRef: '/reading-list'
    weight: -107
  - name: About
    pageRef: /about
    weight: -106

########################################################################################
## Menu documentation: https://gohugo.io/content-management/menus/#properties-front-matter
## The name of menu
# name:
## The ID of menu.
# identifier:
## The weight of menu that used for sorting in ascending order.
# weight:
## The `identifier` of parent menu entry.
# parent:
## The URL of menu.
# url:
## The leading string before menu name.
# pre:
## The trailing string after menu name.
# post:
## Menu parameters.
# params:
#   ## true means divider.
#   divider:
#   ## The icon HTML.
#   icon:
#   ## The description for top app bar dropdown menus only.
#   description: